%% test script
%% 2D
p = [4.54; 6.92];
box_center = [0.0; 0.0];
box_size = [2; 2];
box_yaw = 0*deg2rad(30);
box_vert = box2PolyVertsCons_2D(box_center, box_size, box_yaw);
tic
[a, b] = point_polytope_shifted_hyperplane(p, box_vert);
toc
hfig = figure;
box on;
grid on;
axis([-3 3 -3 3]);
ax = hfig.CurrentAxes;
daspect(ax, [1 1 1]);
hold on;
plot(p(1), p(2), 'o');
hb = plot_poly_vert_2D(ax, box_vert, ...
    'FaceColor', [0.4 0.4 0.4], ...
    'FaceAlpha', 0.2, ...
    'EdgeColor', [0.4 0.4 0.4], ...
    'EdgeAlpha', 0.6, ...
    'LineWidth', 1.0, ...
    'LineStyle', '-.', ...
    'SpecularStrength', 0.1, 'AmbientStrength', 0.5);
dim = [-3 3; -2 2];
hl = plot_line_2D(ax, a, b, dim, ...
    'Color', [0.4 0.4 0.4], ...
    'LineStyle', '--', ...
    'LineWidth', 1.5);